### ISSUE TITLE
Things needed before tagging 0.1

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/AtomsBuilder.jl#7]
I found this package extremely handy over the past months and started using it a lot in my workflows. I wanted to suggest tagging a `0.1`, which at least gives some compatibility guarantees moving forward. So I wanted to hear if there are any blockers for this @cortner and how one could help to remove those.

**Comment by cortner** [comment]
Let me review what it has so far and what is missing in my case. In principle I'm open to that.

**Comment by cortner** [comment]
I guess there is nothing blocking to register 0.1 if it is useful for more than 1 person. I could simply update `Project.toml` and register a new version. Is this what you are suggesting?

**Comment by mfherbst** [comment]
Yes, that would be what I had in mind. Thanks !
